apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kav7zxokt-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:cacc55ada1278d6dfd255d800ef7f3ddeb13ed39@sha256:b6c3f8784516542d9a7deacf84ef5fbb7f12eea9d4c9067029a26626f5ea60df
          name: container-image
