apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kav7zxokt-python 
  janus-idp.io/tekton: kav7zxokt-python
  backstage.io/kubernetes-id: kav7zxokt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kav7zxokt-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  