apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kav7zxokt-python-gitops
  description: This is GitOps manifest for kav7zxokt-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kav7zxokt-python
    janus-idp.io/tekton: kav7zxokt-python
    backstage.io/kubernetes-id: kav7zxokt-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kav7zxokt-python
